### ISSUE TITLE
question about free energy calculation and error messages

### ISSUE THREAD

**Issue by ZAhra-Rjz** [ICAMS/calphy#124]
Hi, 
I am a new calphy user. I have a SiC surface and want to calculate free energy for my system. I tried to write an input script by following Calphy rules but when I ran it, I got this error message:

**KeyError: 'reference_phase'**, **also I got another error about an invalid string for lattice**

Can you check my script and guide me, please?

**This is my input script:**
element: ['C', 'Si']
mass: [12.0107, 28.0855]

calculations:
- mode: ts
  temperature: [2100, 2400]
  pressure: [1]
  lattice: ["/home/calphy/examples/SiC/4h.data"]
  state: [solid]
  nsims: 1

md:
  pair_style: meam
  pair_coeff: "* * ../potentials/library.meam Si C potentials/SiC.meam Si C"
  timestep: 0.001
  npt: True
  tdamp: 0.1
  pdamp: 0.1
  te: 25000
  ts: 50000

queue:
    commands:
    - conda activate calphy
    cores: 4
    scheduler: local

**Comment by srmnitc** [comment]
@ZAhra-Rjz Thanks! Unfortunately the example you are running is an outdated one. Please try one from [here](https://github.com/ICAMS/calphy/tree/main/examples) prefixed with `example_01` to `example_12`
