### ISSUE TITLE
cannot use calphy for MEAM potential

### ISSUE THREAD

**Issue by ZAhra-Rjz** [ICAMS/calphy#127]
Hi,
I want to run calphy with MEAM potential and although i have lammps and always use MEAM and ACE potential, when I run calphy for those potentials i get this error message:
 
Exception: ERROR: No MEAM parameter file in pair coefficients (src/MEAM/pair_meam.cpp:238)
    raise self.lmp._lammps_exception

and this is my pair_coeff command in calphy script:
'* * ../potentials/library.meam Si C SiC.meam Si C'

can you tell me what is the problem?

**Comment by srmnitc** [comment]
@ZAhra-Rjz This is likely happening because it cannot find the `SiC.meam` file, maybe changing it to `'* * ../potentials/library.meam Si C ../potentials/SiC.meam Si C'` would work. Please try this, and if it works, please close the issue. Thanks for reporting!

**Comment by ZAhra-Rjz** [comment]
Thank you for your answer. 
First I tried the way you mentioned but unfortunately, with that command I got the same error message. 
Do you have any suggestions?

**Comment by srmnitc** [comment]
Could you please post your complete input file?

**Comment by ZAhra-Rjz** [comment]
here is my calphy input script:

calculations:
- element: ['C', 'Si']
  lattice: SiC.data
  mass: [12.0107, 28.0855]
  md:
    barostat_damping: 0.1
    equilibration_control: nose_hoover
    thermostat_damping: 0.1
    timestep: 0.001
  mode: ts
  n_equilibration_steps: 10000
  n_iterations: 1
  n_switching_steps: 25000
  pair_coeff: '* * ../potentials/library.meam Si C ../potentials/SiC.meam Si C'
  pair_style: meam
  pressure: 0.0
  queue:
    commands:
    - conda activate calphy
    cores: 4
    scheduler: local
  reference_phase: solid
  repeat:
  - 5
  - 5
  - 5
  temperature:
  - 2100.0
  - 2400.0

**Comment by srmnitc** [comment]
The input file also looks good to me, there should be a simulation file created, within which there is a log.lammps file. Could you please also attach it here?

**Comment by ZAhra-Rjz** [comment]
[log.lammps.docx](https://github.com/ICAMS/calphy/files/14849355/log.lammps.docx)

this is the log file. can you open it?
i couldn't import the original file

**Comment by srmnitc** [comment]
Thanks, I was able to look at it. The issue seems to be that the paths are not corrected for both files. From the log file it seems the full path to your potential file is `/home/zar/calphy2/calphy/examples/potentials/`. Could you please change the command to `* * /home/zar/calphy2/calphy/examples/potentials/library.meam Si C /home/zar/calphy2/calphy/examples/potentials/SiC.meam Si C` and see if that works? Thanks!

**Comment by ZAhra-Rjz** [comment]
it is running with your command. I will let you know if I get any error messages.
Thank you
