### ISSUE TITLE
ImportError: cannot import name 'cumtrapz' 

### ISSUE THREAD

**Issue by stefanhiemer** [ICAMS/calphy#136]
Hi there,

1. Thanks for the nice package!  
2.  I installed calphy according to instructions. When trying to use calphy for the free energy tutorial I get this error:
ImportError: cannot import name 'cumtrapz' from 'scipy.integrate'

It seems that calphy relies on a deprecated command cumtrapz in its integrators.  It should be replaced by the newer cumulative_trapezoid. I already fixed it in a backwards compatible fashion: 

https://github.com/stefanhiemer/calphy/tree/main

If that is fine for you, I would do a pull request.

3. After the fix it still does not run properly. When I try the free energy tutorial I get this error back:

[fe-bcc-solid-100-0.sub.err.txt](https://github.com/user-attachments/files/16083369/fe-bcc-solid-100-0.sub.err.txt)

It cannot locate the potential. Any idea where the issue might lie?

My OS is Fedora 40, Python version 3.12.4 and I use Anaconda3-2023.07-2-Linux-x86_64.

**Comment by stefanhiemer** [comment]
Nevermind point 3. My problem was, that calphy assumes the potentials to lie in a specific place and not some internal, automatically detected database or similar. It would be good to give a hint in the Examples section at the start or somewhere.

Regards
Stefan

**Comment by srmnitc** [comment]
@stefanhiemer  thanks for pointing this out, it would be great if you could open a PR. Thanks again!

**Comment by stefanhiemer** [comment]
No problem. The PR is done.
