### ISSUE TITLE
Error while using MACE potential

### ISSUE THREAD

**Issue by bjn123** [ICAMS/calphy#138]
Dear Developer,
I have followed all the steps to install LAMMPS and Calphy. The default examples are working fine with Calphy. It is noted that LAMMPS is properly installed with ML-MACE. The standalone LAMMPS with MACE potential is functioning well. However, when I try to run Calphy with the MACE potential, Calphy stops at:

```
calphy.helpers INFO     pair_coeff: * * /home/bjnagare/Na-phase-diagram/example_01/2024-01-07-mace-128-L2_epoch-199.model-lammps.pt Na
```

Can you help me resolve this issue?

Thanks in advance,

bjn

**Comment by bjn123** [comment]
Dear sir,
Thank for kind support.

Please see the attached files. lammps.log file is not created during the simulation. 

Thank you
bjn
[calphy-na.zip](https://github.com/user-attachments/files/16313451/calphy-na.zip)

**Comment by srmnitc** [comment]
Thanks! The error file in the folder gives the reason:

```
ValueError: Mode should be either fe/ts/mts/alchemy/melting_temperature/tscale/pscale/composition_scaling
```

Looking at the input file, you have `mode: Na`, which is not correct. Likely you might want to use `mode: fe`.

I will now close this issue. Please feel free to reopen if this persists.
