### ISSUE TITLE
Calphy fails with MEAM potential

### ISSUE THREAD

**Issue by stefanhiemer** [ICAMS/calphy#139]
Hi there,

I tried to run calculations with two different MEAM potentials for chromium and both fail. When I check the lammps log I see this error message:

ERROR: No MEAM parameter file in pair coefficients (src/MEAM/pair_meam.cpp:229)
Last command: pair_coeff * * /home/shiemer/projects/hea/calphy/free_energy/Cr/library.meam Cr Cr.meam Cr

My impression is that your parser only gives the correct path for the library file, but not the meam file.

Attached are the potentials and calphy yamls:

[meam-fail.zip](https://github.com/user-attachments/files/16312796/meam-fail.zip)

**Comment by srmnitc** [comment]
@stefanhiemer correct analysis from your side. Related to https://github.com/ICAMS/calphy/issues/127. If you add complete path for both files it should work. Thanks!

**Comment by stefanhiemer** [comment]
Thanks for the quick answer!

**Comment by srmnitc** [comment]
@stefanhiemer please feel free to close this issue if its resolved.

**Comment by stefanhiemer** [comment]
Worked! Two questions for the future: 
1. Where can I find the source code for the parser? I might edit it to encounter this issue in the future if I find the time the next month.
2. To which degree are the tutorials reproducible? When I tried them I got results for the melting points that where ~50 K below the reported ones in the docu.

**Comment by srmnitc** [comment]
@stefanhiemer The source code is here: https://github.com/ICAMS/calphy/blob/main/calphy/input.py#L321

For the examples, I would expect these changes. This is because they are small system sizes, short switching times, and probably pressure convergence on the less strict side. Once these things are optimized, it should do better.
