### ISSUE TITLE
Slurm scheduler does not work: KeyError: 'queuename'

### ISSUE THREAD

**Issue by stefanhiemer** [ICAMS/calphy#140]
Hi there,

when trying to use calphy with conda on our cluster it fails with the attached error message. 
[error_message.txt](https://github.com/user-attachments/files/16432200/error_message.txt)

The problem is that in scheduler.py: the dictionary for the queueoptions in line 91 is not initialized with the queue name which causes then an error when trying to write out the different Slurm options in the lines following 126 as you try to call a key that has never existed. Please have a look at the pull requests to check whether you like the fix. Please check before on your cluster as well as to my experience cluster configs can be wildly different and the cluster on which I tested is fairly old.

Regards
Stefan

**Comment by srmnitc** [comment]
I did receive this issue, and I have now merged in your PR.

**Comment by srmnitc** [comment]
Thanks a lot for the fix!
