### ISSUE TITLE
Inconvenient handling of filepaths for potentials and structure files

### ISSUE THREAD

**Issue by Leimeroth** [ICAMS/calphy#15]
Specifying a lattice file as shown in the documentation (f.e. as conf.data) throws an error because the file is not found. It works when specifying the full path to the file.

Similarly  a potential file that is in the same directory as the input file and specified as f,e, "potfile.eam" is not found but instead one has to specify "../potfile.eam".  Specifying structure files using ../conf.data does not work.

This is not really a bug, but I think it would be nice to mention it in the Documentation or handle by copying the files to the working directory of the calculations.

**Comment by srmnitc** [comment]
@Leimeroth thanks for this issue! I added a fix to automatically change paths to absolute ones. Should be fixed in v 0.7.1.
