### ISSUE TITLE
temperature sweep with different starting temperatures

### ISSUE THREAD

**Issue by Leimeroth** [ICAMS/calphy#19]
I tried to calculate the melting point of Ga potentials by doing a temperature sweep and than comparing free energies of liquid and solid phase. Now I am facing the problem that the results highly depend on the starting temperature of the temperature sweep.

Temperature sweeps were done from 50, 150, 250 and 350K to 550K respectively. The resulting melting point varies from not existent to slightly below 400K. When using low starting temperatures the Solid and Liquid free energy never cross, because the free energy of the solid decreases faster than that of the liquid. I don' really understand why this happens, because the structures start to melt when increasing the upper temperature limit, which led me to assume that the potential itself is at least reasonable.
The calculated free energy values depend heavily on the starting temperature for the solid and the liquid phase. For the solid the increase with increasing temperature, for the liquid they decrease.

Please find attached the input data and plots of the results. The only change in the input file for each calculation is a changed start temperature. It would be great if you could have a look at this, since I can't tell if this is some bug or me doing something wrong.
[Input.zip](https://github.com/ICAMS/calphy/files/7691120/Input.zip)
[Results.zip](https://github.com/ICAMS/calphy/files/7691169/Results.zip)

**Comment by srmnitc** [comment]
@Leimeroth Thanks for the report. I will check and get back to you.

**Comment by srmnitc** [comment]
@Leimeroth , I think you are doing everything correct. It seems that if you start above 250K, the free energies are consistent. calphy only has vibrational contributions, so in principle, below the Debye temperature, it will be inaccurate. 250 K is likely high enough for the calculations. I think I only mention this in the paper, I will add a word of warning to the documentation.
