### ISSUE TITLE
Running example 4 results in TypeError

### ISSUE THREAD

**Issue by SebastianHavens** [ICAMS/calphy#43]
When example 4 is executed (calphy -i input.yml), it results in the following output:

> Total number of 1 calculations found
> Traceback (most recent call last):
>   File "/home/sebastian/software/miniconda3/envs/calphy/bin/calphy", line 33, in <module>
>     sys.exit(load_entry_point('calphy==1.2.0', 'console_scripts', 'calphy')())
>   File "/home/sebastian/software/miniconda3/envs/calphy/lib/python3.10/site-packages/calphy-1.2.0-py3.10.egg/calphy/kernel.py", line 106, in main
>     run_jobs(args["input"])
>   File "/home/sebastian/software/miniconda3/envs/calphy/lib/python3.10/site-packages/calphy-1.2.0-py3.10.egg/calphy/kernel.py", line 60, in run_jobs
>     identistring = calc.create_identifier()
>   File "/home/sebastian/software/miniconda3/envs/calphy/lib/python3.10/site-packages/calphy-1.2.0-py3.10.egg/calphy/input.py", line 597, in create_identifier
>     identistring = "-".join([prefix, l, str(ts), ps])
> TypeError: sequence item 3: expected str instance, int found

**Comment by srmnitc** [comment]
closed with #44
