### ISSUE TITLE
Need to "install" calphy

### ISSUE THREAD

**Issue by Leimeroth** [ICAMS/calphy#55]
Since calphy is a pure python library it would be great to be able to run it without having to "install" it, since no compilation is required.
This could cause trouble with dependencies, but it would make fast tests and debugging easier.
As far as I can tell this would only require to have the calphy and calphy_kernel scripts directly available or am I missing something?

**Comment by srmnitc** [comment]
This is correct,  calphy and calphy_kernel scripts should be available in an accessible location. The other imports should also be possible of course.
