### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, ' '.

### ISSUE THREAD

**Issue by janklinux** [ICAMS/calphy#61]
Moi,
I am trying to run a QUIP potential with lammps but it does not work. QUIP is fully supported. The persistent error is:

`File "/usr/local/Miniconda/lib/python3.9/site-packages/pylammpsmpi/utils/lammps.py", line 90, in _receive
    output = pickle.load(self._process.stdout)
_pickle.UnpicklingError: invalid load key, ' '.`

 I can provide the complete output if needed, it's long and stems from 

`File "/usr/local/Miniconda/lib/python3.9/site-packages/calphy/solid.py", line 147, in run_averaging
    lmp.command('include {}'.format(self.calc.potential_file))`

originally. I have looked through the examples but there is nothing that provides help for a potential like that. basically I need to include two lines (I wanted to try in two ways):

pair_style quip
pair_coeff * * name.xml "Potential label=GAP_blala" 15 28

while this line needs the quotes, which I suspect are part of  the problem of internal stdin._send and ._receive procedures. 
I have also tried added on option with pair_style quip and pair_coeff to the calphy input file but that produces the exact same error. I am running lammps on a regular basis with quip potentials so the error does not come from there. The potential itself is also tested and reliable. 

At this point, the computations don't even start.

Any help would be appreciated, Jan

**Comment by Leimeroth** [comment]
Sounds very similar to the issue with MTPs #47.
I thought the problem is caused by a problem of the MLIP-LAMMPS interface, since that is not an official lammps package,
but with QUIP being officially supported maybe there is another problem.

**Comment by srmnitc** [comment]
@janklinux I have a feeling that this error is somehow related to pylammpsmpi. I would like to run a couple of tests. Could you please point me to (any) QUIP potential files and also the corresponding pair_coeff and pair_style commands? A minimal working lammps script would be even better. Thanks!

**Comment by janklinux** [comment]
A lammps input is:

```
units           metal
newton          on
dimension       3
boundary        p p p
atom_style      atomic

read_data coo         # from where coordinates are read                                     

pair_style quip
pair_coeff * * natrium.xml "Potential xml_label=GAP_2023_1_19_120_12_7_47_339" 11
mass 1 22.99

neigh_modify    every 1 delay 0 check yes

compute         _rg all gyration

min_style       cg                                    # The algoritm of relaxation             
min_modify      line backtrack                        # The parameters of minimzation algoritm 
fix 1 all npt temp 50 50 1 iso 1000 1000 1  
dump            1 all xyz 50 out.xyz                      # Record animation every 50 steps  

dump_modify     1 append yes

run 1000
```

which runs in a few seconds to normal exit. Do you need the potantials and coordinates too? If you want to actually run lammps you need to have it compiled with quip, too.

**Comment by srmnitc** [comment]
Thank you, I would need potential files too if that is okay. I can compile with quip, no issues.

**Comment by janklinux** [comment]
No problem, you can download it from https://numphys.org/~jank/na.tar.xz

**Comment by janklinux** [comment]
any news on this?

**Comment by srmnitc** [comment]
I can confirm the error is from pylammpsmpi. I am working on a "basic mode" which would use direct LAMMPS so as to overcome this (and #47 ). I think we should have a solution this week.

**Comment by srmnitc** [comment]
There is a new development on pylammpsmpi (https://github.com/pyiron/pylammpsmpi/pull/97). Once released, this could solve the issue.

**Comment by janklinux** [comment]
works fine, problem fixed, thanks
