### ISSUE TITLE
ERROR: Illegal velocity create command

### ISSUE THREAD

**Issue by SebastianHavens** [ICAMS/calphy#82]
Hi,
Sometimes when a melting temperature calculation is being performed, an illegal velocity command is being used with the langevin fix.
I've attached all of the files associated with the run. You may notice that it is not printing a copy of the input files into the main calphy.log file, this is because it can cause calphy to crash, this is the only modification which has been made to calphy.

You can find the log.lammps file of interest in ts-FCC-1528-1000
[crash.tar.gz](https://github.com/ICAMS/calphy/files/12598964/crash.tar.gz)

**Comment by SebastianHavens** [comment]
I've also just seen this:
ERROR: Illegal fix langevin command (src/fix_langevin.cpp:83)
Last command: fix              f2 all langevin 1528.000000 1528.000000 0.100000 0 zero yes

Now I believe that both issues are arising from the 1/10000 chance that the seed is being chosen to be 0

**Comment by srmnitc** [comment]
closed with #83
