### ISSUE TITLE
lattice files are overwritten when structure creation is used

### ISSUE THREAD

**Issue by gswylq** [ICAMS/calphy#88]
Hello every,
According to the developer's suggestion, I have successfully installed calphy-1.2.12. But the calculated results of Example 02 are inconsistent with the results of the tutorial, and the Fe-BCC-FCC phase transition does not occur.
I hope you can give me some advice.

Q. Li

![fe_transition_new](https://github.com/ICAMS/calphy/assets/84161015/ccbf3f64-aec3-4031-93d9-b378f821c4c1)
![Fe_Trans_old](https://github.com/ICAMS/calphy/assets/84161015/82b34856-27d3-4682-aae1-7e5943e69629)
[example_02_new.zip](https://github.com/ICAMS/calphy/files/13073345/example_02_new.zip)

**Comment by srmnitc** [comment]
Thanks for raising this bug. This is due to a bug where the structure file is being overwritten when two calculations are run at the same time. I will fix this soon.

**Comment by srmnitc** [comment]
Fixed in 07bd77e0045e942c22174a957be9ad436da4a7b2. Updating to v1.2.13 should fix the issue. A better solution is needed, so I will keep the issue open until then.

**Comment by srmnitc** [comment]
Fixed properly in #91
